soloistrc works on macOS Sierra
- updated README with instructions for macOS Sierra
  - removed trailing whitespace of dubious origin
- removed `qt`; fixes:
```
This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility
```
- removed `menumeters`; fixes:
```
menumeters # Error: Cask menumeters depends on macOS release <= 10.10, but you are running release 10.12.
```
- removed `bittorrent-sync`; fixes:
```
Error: No available Cask for bittorrent-sync
```